### ISSUE TITLE
Concealed character count not considered for line wrapping

### ISSUE THREAD

**Issue by jaythomas** [calebsmith/vim-lambdify#11]
Typically a wrapped line would look like this:
![line-wrapping2](https://cloud.githubusercontent.com/assets/2344456/10646820/636b3468-7803-11e5-97df-4c3b301b1989.png)

But when concealing text, the line still breaks at the same spot, leaving a blank space that it's not utilizing:
![line-wrapping](https://cloud.githubusercontent.com/assets/2344456/10646844/7bf72d52-7803-11e5-85c7-3a7b759e301b.png)

Wasn't sure how to show this without a screenshot, so excuse the strange PNG coloring...

**Comment by calebsmith** [comment]
Interesting problem. Thanks for noticing and taking a screenshot because that is a bit hard to explain in words.

I suspect this is a problem with using Vim's conceal feature in general. I'm open to a solution if one exists but I suspect that this isn't fixable within this or any plug-in.

If someone has time, it might be possible to dig a bit by setting the conceallevel and concealcursor settings differently. Specifically,  I'm not sure if conceallevel 2 will do something closer to what we want here.

I'll leave this ticket open for so folks can investigate. I'm uncertain if it can be solved.

Thanks again for filing the issue

**Comment by adelarsq** [comment]
This is a Vim behavior that cannot be solved.
There is no solution for this issue.

**Comment by calebsmith** [comment]
Thanks for opening the ticket @jaythomas and investigating @adelarsq . I'll close this ticket with the belief that Adelar and I are correct in thinking this is a problem with vim.

So far, I've just sort of ignored this problem though I realize it is annoying

@jaythomas I appreciate that you found this problem. Feel free to file a ticket with a vim issue tracker to see if you get some traction. We can reopen if anyone is able to find a work around
